<a href="https://colab.research.google.com/github/niteshpdl/Training_Pipeline/blob/main/Training_Pipeline_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.shape


(569, 33)

In [ ]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)


In [ ]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,1:],df.iloc[:, 0], test_size=0.2)

In [ ]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
x_train

array([[-1.78516435,  1.18228777, -1.79230598, ..., -1.74983677,
        -0.10598678, -0.77624064],
       [ 0.74896389,  0.01427548,  0.65379249, ..., -0.49334372,
        -0.6755679 , -1.35124139],
       [-0.85858882, -0.13057644, -0.76581823, ...,  2.00951416,
         2.01835213,  2.99117287],
       ...,
       [-0.88928862, -0.50535203, -0.82931649, ...,  0.56624512,
        -0.65404303,  0.56722408],
       [-1.55156684, -0.18345888, -1.54276188, ..., -1.74983677,
         0.34272394, -0.19585095],
       [-0.07155781, -0.03630773, -0.14175574, ..., -0.53594176,
        -0.9587027 , -0.47230398]])

In [ ]:
y_train

568    B
157    B
379    M
504    B
284    B
      ..
82     M
326    B
440    B
314    B
481    B
Name: diagnosis, Length: 455, dtype: object

In [ ]:
encoder = LabelEncoder()

# Fit and transform the training labelsy_tr
y_train = encoder.fit_transform(y_train)

# Transform the testing labels (no fitting here to ensure consistent encoding)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [ ]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
x_train_tensor

tensor([[-1.7852,  1.1823, -1.7923,  ..., -1.7498, -0.1060, -0.7762],
        [ 0.7490,  0.0143,  0.6538,  ..., -0.4933, -0.6756, -1.3512],
        [-0.8586, -0.1306, -0.7658,  ...,  2.0095,  2.0184,  2.9912],
        ...,
        [-0.8893, -0.5054, -0.8293,  ...,  0.5662, -0.6540,  0.5672],
        [-1.5516, -0.1835, -1.5428,  ..., -1.7498,  0.3427, -0.1959],
        [-0.0716, -0.0363, -0.1418,  ..., -0.5359, -0.9587, -0.4723]],
       dtype=torch.float64)

In [ ]:
y_train_tensor.shape

torch.Size([455])

In [ ]:
class MySimpleNN():
  def __init__(self, x):
    self.weights = torch.rand(x.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward (self, x):
    return torch.matmul(x, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
    loss = -(y_train_tensor * torch.log(y_pred) + (1-y_train_tensor) * torch.log(1-y_pred)).mean()
    return loss


In [ ]:
learning_rate=0.1
epochs = 25

In [ ]:
model = MySimpleNN(x_train_tensor)
for epoch in range(epochs):
  y_pred = model.forward(x_train_tensor)
  loss = model.loss_function(y_pred, y_train_tensor)
  loss.backward()
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad
  model.weights.grad.zero_()
  model.bias.grad.zero_()
  print(f'Epoch {epoch+1}, Loss: {loss.item()}')

Epoch 1, Loss: 7.376387949246896
Epoch 2, Loss: 7.3746955639415726
Epoch 3, Loss: 7.3744737756180605
Epoch 4, Loss: 7.3742872790207885
Epoch 5, Loss: 7.374123020269189
Epoch 6, Loss: 7.37397515857129
Epoch 7, Loss: 7.373840359553891
Epoch 8, Loss: 7.373716403072844
Epoch 9, Loss: 7.373601669131633
Epoch 10, Loss: 7.373494909423588
Epoch 11, Loss: 7.373395128539037
Epoch 12, Loss: 7.373301514019635
Epoch 13, Loss: 7.373213391242279
Epoch 14, Loss: 7.373130192398522
Epoch 15, Loss: 7.373051434196654
Epoch 16, Loss: 7.37297670131877
Epoch 17, Loss: 7.372905633856224
Epoch 18, Loss: 7.3728379175910135
Epoch 19, Loss: 7.372773276365924
Epoch 20, Loss: 7.3727114660187025
Epoch 21, Loss: 7.372652269506325
Epoch 22, Loss: 7.372595492947142
Epoch 23, Loss: 7.372540962379118
Epoch 24, Loss: 7.360174815519876
Epoch 25, Loss: 7.327017704915944


In [ ]:
model.weights

tensor([[ 0.3919],
        [ 0.9164],
        [ 0.3912],
        [ 0.6950],
        [-0.1815],
        [ 0.1595],
        [ 0.7715],
        [ 0.3379],
        [ 0.2998],
        [ 0.5480],
        [ 0.2227],
        [ 1.0246],
        [ 0.0388],
        [ 0.4572],
        [ 0.7436],
        [ 0.6641],
        [ 0.8372],
        [ 0.0288],
        [ 0.2320],
        [ 0.6043],
        [ 0.1931],
        [ 0.6745],
        [ 0.3572],
        [ 0.1721],
        [ 0.2779],
        [ 0.0357],
        [ 0.7362],
        [ 0.4606],
        [ 0.8545],
        [ 0.4056]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.bias

tensor([-0.2445], dtype=torch.float64, requires_grad=True)

In [ ]:
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5523238182067871
